'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import type {Copy} from '@/lib/content';
export function Contact({c}:{c:Copy['contact']}){
 const [state,setState]=useState('idle'),[error,setError]=useState('');const heading=useRef<HTMLHeadingElement>(null); const endpoint=process.env.NEXT_PUBLIC_LEAD_ENDPOINT||'';
 useEffect(()=>{if(state==='prepared'||state==='sent')heading.current?.focus();},[state]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget;const data=new FormData(f); const name=String(data.get('name')||'').trim(),contact=String(data.get('contact')||'').trim();if(!name||!(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(contact)||/^@[A-Za-z][A-Za-z0-9_]{4,31}$/.test(contact))){setError(c.invalid);(f.elements.namedItem(!name?'name':'contact') as HTMLInputElement)?.focus();return;}if(data.get('website'))return;setError('');setState('sending');const params=new URLSearchParams(location.search);const payload={name,contact,organization:String(data.get('organization')||'').trim(),ticket:String(data.get('ticket')),dataRoom:data.get('dataRoom')==='on',consent:true,ref:params.get('ref')||'',utm:Object.fromEntries([...params.entries()].filter(([k])=>k.startsWith('utm_')))};
 try{if(endpoint){const result=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal:AbortSignal.timeout(12000)});if(!result.ok)throw new Error();setState('sent');}else{const url=URL.createObjectURL(new Blob([[c.notSent, '', `${c.name}: ${payload.name}`, `${c.email}: ${payload.contact}`, `${c.org}: ${payload.organization}`, `${c.range}: ${payload.ticket}`, `${c.room}: ${payload.dataRoom?c.yes:c.no}`, `${c.consent}: ${c.yes}`].join('\n')],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=c.file;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setState('prepared');}}catch{setState('idle');setError(c.error);}}
 if(state==='prepared'||state==='sent')return <div className="confirmation" role="status"><span className="micro">07 / 01</span><h3 tabIndex={-1} ref={heading}>{state==='sent'?c.sent:c.success}</h3><p>{state==='sent'?c.sentBody:c.successBody}</p><button className="cta" onClick={()=>setState('idle')}>{c.again} ↗</button></div>;
 return <form className="investor-form" onSubmit={submit}><div className="form-row"><label>{c.name}<input name="name" autoComplete="name" required maxLength={100}/></label><label>{c.org}<input name="organization" autoComplete="organization" maxLength={150}/></label></div><label>{c.email}<input name="contact" required autoComplete="email" aria-invalid={error===c.invalid||undefined} aria-describedby={error===c.invalid?"contact-error":undefined} maxLength={254}/></label><label>{c.range}<select name="ticket">{c.ranges.map(x=><option key={x}>{x}</option>)}</select></label><label className="check"><input type="checkbox" name="dataRoom"/>{c.room}</label><label className="check"><input type="checkbox" name="consent" required/>{c.consent}</label><div className="honey" aria-hidden="true"><label>{c.trap}<input name="website" tabIndex={-1} autoComplete="off"/></label></div>{error&&<p id="contact-error" role="alert" className="form-error">{error}</p>}<button className="cta magnet" disabled={state==='sending'}>{state==='sending'?c.sending:endpoint?c.send:c.submit}<span aria-hidden="true">↗</span></button>{!endpoint&&<p className="assumption">{c.notice}</p>}<p className="privacy">{c.privacy}</p></form>;
}
