'use client';
import {useEffect,useRef} from 'react';
// A generated sequence is deliberately optional. Never fabricate turntable views from a flat photograph.
export function CupSequence({alt,label}:{alt:string;label:string}){const canvas=useRef<HTMLCanvasElement>(null);
 useEffect(()=>{const el=canvas.current;if(!el)return;const reduced=matchMedia('(prefers-reduced-motion: reduce)');let stopped=false;const bitmaps:ImageBitmap[]=[];let frame=0;const stage=el.closest('[data-cup-stage]');let controller:AbortController|undefined;
 const draw=(e:Event)=>{frame=(e as CustomEvent<number>).detail;const b=bitmaps[frame];if(!b||reduced.matches)return;const ctx=el.getContext('2d');if(ctx){el.width=b.width;el.height=b.height;ctx.drawImage(b,0,0);el.dataset.ready='true';}};
 const observer=new IntersectionObserver(async entries=>{if(!entries.some(x=>x.isIntersecting)||reduced.matches)return;observer.disconnect();controller=new AbortController();try{const res=await fetch('/sequence/manifest.json',{signal:controller.signal});const manifest=await res.json();if(!Array.isArray(manifest.frames)||manifest.frames.length!==36)return;for(let i=0;i<36;i++){if(stopped||reduced.matches)break;const blob=await fetch(manifest.frames[i],{signal:controller.signal}).then(r=>r.blob());bitmaps[i]=await createImageBitmap(blob);draw(new CustomEvent('cupframe',{detail:frame}));await new Promise<void>(r=>requestAnimationFrame(()=>r()));}}catch{/* Static product photography remains available. */}},{rootMargin:'100px'});
 const change=()=>{if(reduced.matches){controller?.abort();el.dataset.ready='false';}else if(stage)observer.observe(stage);};if(stage){observer.observe(stage);stage.addEventListener('cupframe',draw);}reduced.addEventListener('change',change);return()=>{stopped=true;controller?.abort();observer.disconnect();stage?.removeEventListener('cupframe',draw);reduced.removeEventListener('change',change);bitmaps.forEach(b=>b.close());};},[]);
 return <><picture><source type="image/avif" srcSet="/drinks/drink-0-480.avif 480w, /drinks/drink-0-960.avif 960w" sizes="(max-width: 767px) 82vw, 440px"/><img src="/drinks/drink-0-480.webp" width="720" height="960" loading="lazy" decoding="async" alt={alt}/></picture><canvas ref={canvas} className="cup-canvas" width={900} height={1200} role="img" aria-label={label}/></>;
}
