'use client';
import {useEffect,useRef,useState} from 'react';
import {calculate,defaults,scenarios,formatMoney,model,type Inputs} from '@/lib/store-model';
import type {Copy,Locale} from '@/lib/content';
export function Economics({c,extra,locale}:{c:Copy['economics'];extra:Copy['economicsExtra'];locale:Locale}){
 const [inputs,setInputs]=useState(defaults),[usd,setUsd]=useState(false),[active,setActive]=useState(1),[custom,setCustom]=useState(false); const ref=useRef<HTMLDivElement>(null);
 const result=calculate(inputs);const money=(n:number)=>formatMoney(n,locale,usd);
 useEffect(()=>{const el=ref.current;if(!el)return;const update=(event:Event)=>{if(custom)return;const i=(event as CustomEvent<number>).detail;setActive(i);setInputs(scenarios[i]);};el.addEventListener('scenario',update);return()=>el.removeEventListener('scenario',update);},[custom]);
 const fields=[{key:'cups',min:0,max:350,step:5},{key:'ticket',min:0,max:260,step:5},{key:'rent',min:0,max:120000,step:5000},{key:'staff',min:0,max:350000,step:10000}] as const;
 const choose=(i:number)=>{setActive(i);setInputs(scenarios[i]);setCustom(true);};
 return <><div className="economics-scroll" data-economics ref={ref}><div className="economics-pin"><div className="model-toolbar"><div className="scenario-tabs" role="group" aria-label={extra.scenario}>{[1,0,2].map(i=><button key={i} type="button" aria-pressed={active===i} onClick={()=>choose(i)}>{c.scenarios[i]}</button>)}</div><fieldset className="currency"><legend className="sr-only">{c.currency}</legend><button type="button" aria-pressed={!usd} onClick={()=>setUsd(false)}>{c.uah}</button><button type="button" aria-pressed={usd} onClick={()=>setUsd(true)}>{c.usd}</button></fieldset></div><div className="model-grid"><div className="sliders">{fields.map(f=><label key={f.key} htmlFor={f.key}><span>{c[f.key]}<output htmlFor={f.key}>{f.key==='cups'?inputs[f.key]:money(inputs[f.key])}</output></span><input id={f.key} type="range" min={f.min} max={f.max} step={f.step} value={inputs[f.key]} aria-valuetext={f.key==='cups'?String(inputs[f.key]):money(inputs[f.key])} onChange={e=>{setCustom(true);setActive(-1);setInputs({...inputs,[f.key]:Number(e.target.value)} as Inputs);}}/></label>)}</div><div className="results"><p className="micro">{c.ebitda}</p><strong className="ebitda" data-ebitda>{money(result.ebitda)}</strong><dl className="result-grid">{[[c.revenue,money(result.revenue)],[c.gross,result.grossMargin===null?c.undefined:`${(result.grossMargin*100).toLocaleString(locale,{maximumFractionDigits:1})}%`],[c.contribution,money(result.contribution)],[c.payback,result.payback===null?c.none:result.payback.toLocaleString(locale,{maximumFractionDigits:1})],[c.breakEven,result.breakEven??c.none]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></div></div><div className="model-bottom micro"><span>{custom?extra.custom:extra.scroll}</span><button type="button" onClick={()=>{setCustom(false);setInputs(defaults);setActive(1);}}>{extra.reset} ↺</button></div></div></div><div className="scenario-comparison">{[1,0,2].map(i=>{const s=scenarios[i],v=calculate(s);return <article key={i}><h3>{c.scenarios[i]}</h3><div className="micro">{s.cups} / {money(s.ticket)}</div><dl><div><dt>{c.revenue}</dt><dd>{money(v.revenue)}</dd></div><div><dt>{c.ebitda}</dt><dd>{money(v.ebitda)}</dd></div><div><dt>{c.payback}</dt><dd>{v.payback?.toLocaleString(locale,{maximumFractionDigits:1})??c.none}</dd></div></dl></article>})}</div><div className="model-assumptions"><p className="micro">{extra.tag}</p><p className="assumption">{c.assumptions}</p><p className="assumption">{c.explanation}</p><p className="assumption">{c.zeroNote}</p><div className="baseline micro"><span>{extra.funding} / {money(model.funding)}</span><span>{extra.exchange} / {model.fx} {c.uah} = 1 {c.usd}</span></div></div></>;
}
