import type { CSSProperties } from 'react';
import { getCopy, pathFor, languageTag, type Copy, type Locale } from '@/lib/content';
import { calculate, scenarios, model, formatMoney } from '@/lib/store-model';
import { Runtime } from './Runtime';
import { Economics } from './Economics';
import { Contact } from './Contact';
import { LanguageSwitcher } from './LanguageSwitcher';
import { ProductInventory } from './ProductInventory';
import { LineArt } from './LineArt';
const ids=['thesis','product','market','economics','scale','terms','contact'];
export function Title({lines}:{lines:string[]}){return <h2 className="section-title">{lines.map((line,i)=><span className="reveal-line" key={line}><span style={{'--delay':`${i*60}ms`} as CSSProperties}>{line}</span></span>)}</h2>}
function Head({i,c}:{i:number;c:Copy}){return <div className="section-head"><span>{String(i+1).padStart(2,'0')} / 07</span><span>{c.sections[i]}</span><span aria-hidden="true">+</span></div>}
function Num({v,decimals=0,suffix='',locale}:{v:number;decimals?:number;suffix?:string;locale:Locale}){const n=new Intl.NumberFormat(locale,{maximumFractionDigits:decimals,minimumFractionDigits:decimals}).format(v);return <span className="number" data-count={v} data-decimals={decimals} data-suffix={suffix}>{n}{suffix}</span>}
export function System({locale='uk',view='all'}:{locale?:Locale;view?:'all'|'menu'|'investors'}){
 const c=getCopy(locale); const visible=(id:string)=>view==='all'||(view==='menu'?['product','contact'].includes(id):['market','economics','scale','terms','contact'].includes(id));
 const here=view==='all'?'':view; const home=pathFor(locale);
 return <div lang={languageTag(locale)} className="system"><Runtime locale={locale}/><a href="#main" className="skip">{c.nav.skip}</a>
 <header className="topbar"><a href={home} className="wordmark" aria-label={c.brand+' / '+c.nav.home}>{c.brand}</a><span className="edition">{c.edition}</span><nav aria-label={c.nav.label}><a href={pathFor(locale,'menu')}>{c.nav.menu}</a><a href={pathFor(locale,'investors')}>{c.nav.investors}</a><LanguageSwitcher locale={locale} path={here} label={c.nav.language}/></nav></header>
 <aside className="rail"><nav aria-label={c.nav.index}>{ids.filter(visible).map(id=><a key={id} href={`#${id}`} data-section-link={id}><span>{String(ids.indexOf(id)+1).padStart(2,'0')}</span><span>{c.sections[ids.indexOf(id)]}</span></a>)}</nav><span className="reading-progress" aria-hidden="true" data-progress-label>00%</span></aside>
 <div className="top-progress" aria-hidden="true"><i/></div><main id="main" tabIndex={-1}>{view!=="all"&&<h1 className="sr-only">{view==="menu"?c.nav.menu:c.nav.investors}</h1>}
 {visible('thesis')&&<section id="thesis" className="section thesis"><Head i={0} c={c}/><p className="micro status">{c.status}</p><div className="hero-layout"><div className="hero-story"><h1>{c.thesis.map(line=><span key={line}>{line}</span>)}</h1><p className="hero-lead">{c.hero.lead}</p><p className="hero-body">{c.hero.body}</p><div className="hero-actions"><a href="#economics">{c.hero.model}<span aria-hidden="true">↗</span></a><a href="#contact">{c.hero.partner}<span aria-hidden="true">↗</span></a></div></div><LineArt kind="sprout" className="hero-sketch"/></div><div className="thesis-foot"><span>{c.thesisFoot[0]}</span><span>{c.thesisFoot[1]}</span><a className="magnet arrow-link" href="#product" aria-label={c.sections[1]}>↓</a></div></section>}
 {visible('product')&&<section id="product" className="section product product-catalog"><Head i={1} c={c}/><ProductInventory locale={locale} c={c.catalogue}/></section>}
 {visible('market')&&<section id="market" className="section market"><Head i={2} c={c}/><Title lines={c.market.title}/><div className="market-grid">{[{label:c.market.world,from:3.35,to:3.62,y1:'2025',y2:'2026',cagr:8.4,source:0,decimals:2},{label:c.market.europe,from:727.2,to:1262.6,y1:'2026',y2:'2033',cagr:8.2,source:1,decimals:1}].map((x,i)=><article key={x.label} className="market-card"><p className="micro">{x.label}</p><div className="chart-values"><div><strong><Num v={x.from} decimals={x.decimals} locale={locale}/></strong><small>{x.y1}</small></div><span aria-hidden="true">→</span><div><strong><Num v={x.to} decimals={x.decimals} locale={locale}/></strong><small>{x.y2}</small></div></div><svg className="data-chart" viewBox="0 0 500 100" role="img" aria-label={c.market.chart}><path className="chart-grid" d="M0 24H500M0 60H500M0 96H500M1 0V100M166 0V100M333 0V100M499 0V100"/><g className="chart-reveal"><path className="chart-line" d={i===0?'M1 80L499 12':'M1 90L499 6'}/></g></svg><div className="market-caption"><span><Num v={x.cagr} decimals={1} suffix="%" locale={locale}/> {c.market.cagr}</span><a href={c.sources[x.source].url} target="_blank" rel="noreferrer">{c.sources[x.source].name} ↗</a></div></article>)}</div><div className="market-bottom"><article><span className="micro">{c.market.eu}</span><strong><Num v={10} suffix="%" locale={locale}/></strong><a href={c.sources[2].url} target="_blank" rel="noreferrer">{c.sources[2].name} ↗</a></article><article><span className="micro">{c.market.stores}</span><strong><Num v={4000} suffix="+" locale={locale}/></strong><a href={c.sources[3].url} target="_blank" rel="noreferrer">{c.sources[3].name} ↗</a></article><article><span className="micro">{c.market.overseas}<br/>{c.market.period}</span><strong><span className="micro">{c.market.nearly} </span><Num v={600} suffix="%" locale={locale}/></strong><a href={c.sources[4].url} target="_blank" rel="noreferrer">{c.sources[4].name} ↗</a></article></div><div className="source-foot micro"><span>{c.market.forecast}</span><span>{c.market.historical}</span></div></section>}
 {visible('economics')&&<section id="economics" className="section economics"><Head i={3} c={c}/><Title lines={c.economicsTitle}/><Economics c={c.economics} extra={c.economicsExtra} locale={locale}/></section>}
 {visible('scale')&&<section id="scale" className="section scale"><Head i={4} c={c}/><Title lines={c.scale.title}/><div className="format-grid">{scenarios.map((s,i)=><article className="format" key={i}><div className="format-heading"><span className="micro">0{i+1}</span><h3>{c.scale.formats[i]}</h3><span aria-hidden="true">↗</span></div><div className="format-sketch"><LineArt kind="store"/></div><dl>{[c.scale.areas[i],formatMoney(model.funding,locale),s.cups,calculate(s).payback?.toLocaleString(locale,{maximumFractionDigits:1})].map((v,j)=><div key={j}><dt>{c.scale.labels[j+1]}</dt><dd>{v}</dd></div>)}</dl></article>)}</div><p className="micro scale-repeat">{c.scale.repeat}</p><p className="assumption">{c.scale.note}</p></section>}
 {visible('terms')&&<section id="terms" className="section terms"><Head i={5} c={c}/><Title lines={c.terms.title}/><p className="assumption">{c.terms.tag}</p><dl className="term-facts">{[[c.terms.instrument,c.terms.instrumentValue],[c.terms.ticket,c.terms.ticketValue],[c.terms.return,c.terms.returnValue]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><div className="terms-grid"><div><h3 className="micro">{c.terms.funds}</h3><div className="allocation" aria-hidden="true">{[35,25,20,12,8].map((n,i)=><span key={n} style={{flex:n,'--tone':`${20+i*15}%`} as CSSProperties}/>)}</div><ol className="allocation-key">{c.terms.allocations.map((x,i)=><li key={x}><span>{x}</span><span>{[35,25,20,12,8][i]}%</span></li>)}</ol></div><ol className="gates">{c.terms.gates.map(x=><li key={x}>{x}</li>)}</ol></div><h3 className="micro risks-title">{c.terms.risksTitle}</h3><div className="risks">{c.terms.risks.map(([a,b])=><div key={a}><span>{a}</span><span>→</span><span>{b}</span></div>)}</div><p className="assumption">{c.terms.note}</p></section>}
 {visible('contact')&&<section id="contact" className="section contact"><Head i={6} c={c}/><div className="contact-grid"><div><LineArt kind="conversation" className="contact-sketch"/><Title lines={c.contact.title}/><p className="micro">{c.contact.lead}</p><a className="download magnet" href={`/downloads/xoxo-${locale}.pdf`} download>{c.contact.download}<span>↗</span></a>{process.env.NEXT_PUBLIC_CALENDAR_URL?<a className="download magnet" href={process.env.NEXT_PUBLIC_CALENDAR_URL}>{c.contact.calendarReady}<span>↗</span></a>:<span className="calendar-pending">{c.contact.calendar}</span>}</div><Contact c={c.contact}/></div></section>}
 </main><footer className="footer">{c.footer.map(s=><span key={s}>{s}</span>)}</footer></div>;
}
