import type { Content } from "./uk";

export const en: Content = {
  meta: {
    title: "XoXo Tea — Modern Tea in Ukraine",
    description:
      "XoXo Tea is building a modern tea brand in Ukraine around real tea, fresh fruit, boba and contemporary beverage culture.",
  },
  nav: {
    brand: "xoxo",
    why: "Why Ukraine",
    tea: "Tea",
    economics: "Economics",
    store: "First Store",
    vision: "Vision",
    contact: "Contact",
    open: "Menu",
    close: "Close",
  },
  a11y: {
    skip: "Skip to content",
    home: "Home, XoXo Tea",
    language: "Language",
    primaryNav: "Primary navigation",
    mobileNav: "Mobile navigation",
    localeUk: "Українська",
    localeEn: "English",
    localeRu: "Русский",
  },
  stamps: {
    developmentMenu: "Development menu",
    planningEstimate: "Planning estimate",
    targetFormat: "Target store format",
    modelledPayback: "Modelled payback",
  },
  notFound: {
    code: "404",
    title: "This page is not here.",
    text: "This path is not part of XoXo Tea.",
    back: "xoxo tea →",
  },
  hero: {
    note: "modern tea / made for ukraine",
    title: "xoxo tea",
    statement: "Ukraine is ready\nfor modern tea.",
    support: "Real tea. Fresh fruit. A new beverage category.",
    arrow: "this is where we start →",
    cta: "See more",
    ctaInvestor: "For investors ↓",
  },
  why: {
    kicker: "why ukraine?",
    headline: "Coffee already has a culture.\nTea does not.",
    paragraphs: [
      "Specialty coffee changed how people think about coffee.",
      "Tea has not had the same transformation yet.",
      "Modern tea now sits between tea, fruit, milk, boba, dessert, design and hospitality.",
      "In Ukraine, the category remains fragmented.",
      "We see an opportunity.",
    ],
  },
  gap: {
    headline: "This is modern tea.",
    lede: "Not just bubble tea. Not just a brew. A category between specialty coffee and familiar boba.",
    items: [
      { id: "specialty-coffee", label: "Specialty coffee" },
      { id: "energy", label: "Energy drinks" },
      { id: "soft-drinks", label: "Soft drinks" },
      { id: "juice", label: "Juice" },
      { id: "desserts", label: "Desserts" },
      { id: "bubble-tea", label: "Bubble tea" },
      { id: "modern-tea", label: "Modern tea" },
    ],
    note: "this space is interesting.",
    footnote:
      "A qualitative thesis, not a market-share claim. We are not saying Ukraine has no bubble-tea shops.",
    established: "established category",
    emerging: "new category",
  },
  product: {
    kicker: "start with the product",
    headline: "Great branding will not make people come back.\nThe drink has to.",
    lede: "The launch menu takes its structure from the modern Asian tea category and adapts it for Ukraine.",
    principles: [
      "real brewed tea",
      "fresh fruit",
      "real dairy where it belongs",
      "freshly prepared toppings",
      "controlled sweetness",
      "strong visual presentation",
      "repeatable recipes",
    ],
  },
  menu: {
    kicker: "xoxo ten",
    headline: "Ten cups\nto start with.",
    disclaimer: "*Final recipes and launch prices are currently in development. Expected range, not a locked menu.",
    priceLabel: "expected price",
    drinks: {
      "jasmine-cloud": {
        name: "Jasmine Cloud",
        text: "Clean jasmine underneath. A light salted cloud above. The contrast is the product.",
        note: "tea first →",
        ingredients: ["jasmine", "cloud", "milk"],
      },
      grape: {
        name: "XoXo Grape",
        text: "Fresh grapes and jasmine. Fruit-forward. Tea still audible.",
        note: "fresh grapes →",
        ingredients: ["grape", "jasmine", "ice"],
      },
      "grape-cloud": {
        name: "Grape Cloud",
        text: "Grape, tea, dairy cloud. One of the most important pictures.",
        note: "the money shot →",
        ingredients: ["grape", "jasmine", "cloud"],
      },
      "mango-cloud": {
        name: "Mango Cloud",
        text: "Ripe mango, jasmine, cloud. Made to be photographed.",
        note: "gold →",
        ingredients: ["mango", "jasmine", "cloud"],
      },
      "mango-grapefruit": {
        name: "Mango Grapefruit",
        text: "Mango and grapefruit, no cloud. Bright, acidic, fresh.",
        note: "no cloud →",
        ingredients: ["mango", "grapefruit", "jasmine"],
      },
      "coconut-mango": {
        name: "Coconut Mango",
        text: "Mango, coconut milk, sago. The easiest door in for people who barely drink tea.",
        note: "the friendly one →",
        ingredients: ["mango", "coconut", "sago"],
      },
      "brown-sugar-boba": {
        name: "Brown Sugar Boba",
        text: "Tea, dairy, fresh pearls, brown sugar. A bridge for people who already know boba. Not excessively sweet.",
        note: "the bridge →",
        ingredients: ["tea", "milk", "boba", "brown sugar"],
      },
      "jasmine-milk": {
        name: "Jasmine Milk Tea",
        text: "Strong jasmine and fresh milk. The everyday cup. Nothing extra.",
        note: "every day →",
        ingredients: ["jasmine", "milk"],
      },
      "matcha-cloud": {
        name: "Matcha Cloud",
        text: "Proper matcha, milk, cloud. The green identity.",
        note: "green →",
        ingredients: ["matcha", "milk", "cloud"],
      },
      "triple-matcha": {
        name: "Triple Matcha",
        text: "Matcha, cloud, jelly, mochi. The most indulgent of the ten. Premium.",
        note: "premium →",
        ingredients: ["matcha", "milk", "jelly", "mochi"],
      },
    },
  },
  ingredients: {
    kicker: "what's inside",
    headline: "Nothing extra.",
    items: {
      tea: { title: "Tea", text: "Freshly brewed. Not simply a flavored base." },
      fruit: { title: "Fruit", text: "Actual fruit whenever it is operationally right." },
      milk: { title: "Milk", text: "Real dairy, or a carefully chosen alternative." },
      boba: { title: "Boba", text: "Cooked in controlled batches for texture." },
      cloud: { title: "Cloud", text: "A real cream-cheese dairy cap. Not powder." },
      matcha: { title: "Matcha", text: "Quality powder, prepared properly. Not hidden under sugar." },
    },
  },
  cup: {
    kicker: "one cup",
    headline: "What can one cup\nlook like economically?",
    label: "Illustrative unit economics",
    note: "this is why beverages can scale.",
    price: "selling price",
    ingredients: "ingredients",
    packaging: "cup / straw / packaging",
    direct: "direct product cost",
    profit: "gross profit before labor / rent",
    margin: "gross margin",
    disclaimer: "Illustrative model. This is not audited operating history.",
  },
  ranges: {
    headline: "Ranges, not fake precision.",
    rows: [
      { id: "simpleTea", label: "Simple tea" },
      { id: "milkBoba", label: "Milk / boba" },
      { id: "fruitTea", label: "Fruit tea" },
      { id: "premium", label: "Premium / matcha" },
    ],
    retail: "retail",
    cogs: "direct product cost",
    note: "Initial planning assumptions from recipe modelling. They will move with contracts, season, waste and final formulation.",
  },
  store: {
    kicker: "one store",
    headline: "One store first.\nMykolaiv.",
    area: "about 35–40 m²",
    lede: "Small footprint. High product output. Strong visual identity. Clear flow.",
    zones: ["order", "tea", "fruit", "assembly", "pickup", "storage", "a little seating"],
  },
  startup: {
    kicker: "start",
    headline: "What does the first store cost?",
    total: "illustrative initial investment",
    items: {
      renovation: "renovation / buildout",
      equipment: "equipment",
      furniture: "furniture / signage",
      inventory: "initial inventory / packaging",
      pos: "POS / software / smallwares",
      preopening: "pre-opening / staff / marketing",
      workingCapital: "working capital",
    },
    note: "Planning estimate — final budget depends on site condition, equipment specification and lease terms.",
  },
  scenarios: {
    kicker: "if people like it",
    headline: "What can one store do?",
    formula: "daily orders  ×  average ticket  ×  30 days",
    labels: {
      conservative: "Conservative",
      base: "Base case",
      strong: "Strong store",
    },
    orders: "orders / day",
    ticket: "average ticket",
    monthly: "monthly sales",
  },
  profit: {
    headline: "Gross margin is not net profit.",
    shares: [
      { id: "productPackaging", label: "product / packaging" },
      { id: "labor", label: "labor" },
      { id: "occupancy", label: "rent + utilities" },
      { id: "fees", label: "payments / software" },
      { id: "marketing", label: "marketing" },
      { id: "misc", label: "waste / cleaning / other" },
    ],
    margin: "possible stabilized store-level operating margin",
    possible: "possible store operating profit",
    disclaimer:
      "Scenario model only. Excludes financing structure and may exclude certain taxes, central overhead and extraordinary expenses.",
  },
  calculator: {
    headline: "Move the numbers.",
    label: "Illustrative model",
    orders: "orders / day",
    ticket: "average ticket",
    revenue: "monthly revenue",
    profit: "estimated store profit",
    payback: "modelled payback",
    months: "mo.",
    note: "one small store.",
  },
  payback: {
    headline: "Modelled payback",
    investment: "initial investment",
    profit: "stabilized operating profit",
    result: "roughly",
    not: "not “ROI guaranteed in 12 months.”",
  },
  vision: {
    kicker: "then",
    headline: "The first store\nis not the business.\nThe brand is.",
    lede: "If the first shop proves product-market fit, repeat visits, healthy margins, throughput and recognition — the concept can be copied.",
    steps: ["Mykolaiv", "Prove", "Repeat", "Expand"],
    note: "no fake national timetable.",
  },
  opportunity: {
    items: [
      { code: "01", title: "Category", text: "Modern tea remains underdeveloped locally." },
      { code: "02", title: "Product", text: "Globally proven beverage formats can be adapted to Ukrainian guests." },
      { code: "03", title: "Economics", text: "High beverage gross margins can make a compact store attractive." },
      { code: "04", title: "Brand", text: "There is still room to build a recognizable Ukrainian category leader." },
    ],
  },
  whyXoxo: {
    headline: "The recipes can be copied.",
    lede: "A coherent brand, a guest habit and an operating system are harder.",
    parts: ["product", "design", "operations", "local understanding"],
    note: "make the cup good first.",
  },
  cta: {
    headline: "Let's build\nthe first one.",
    text: "XoXo Tea is developing its first Ukrainian location and launch product system. We want conversations with investors, partners, landlords and suppliers who understand the chance to build a category early.",
    primary: "Discuss investment",
    secondary: "Contact XoXo",
    note: "mykolaiv first →",
  },
  footer: {
    line: "modern tea / ukraine",
    city: "Mykolaiv",
    country: "Ukraine",
    instagram: "Instagram",
    email: "Email",
    investor: "Investors",
  },
};
